### ISSUE TITLE
package "shell" is needed for proper functioning

### ISSUE THREAD

**Issue by beneon** [skandasoft/open-unsupported-files#16]
```coffee
          if extension in @extensions
            if e.detail is 2
              shell = require('shell')
              shell.openItem(path)
            return false
          else
            @originalFileViewEntryClicked.call(tv, e)
```

this package been out of order for sometimes. recently I check the source and found these at the bottom of the code.
the node module 'shell' wasn't included in node_modules, I'm not sure this is an constitutional module of node itself and by running `npm install shell --save-dev` the whole package worked again so I guess the shell package should be included in the package.json after all.

**Comment by weslo** [comment]
If you've got this fixed, please submit a pull request!

**Comment by skandasoft** [comment]
:+1:
