### ISSUE TITLE
Uncaught TypeError: Cannot read property 'data-path' of undefined

### ISSUE THREAD

**Issue by shawnbmiller** [skandasoft/open-unsupported-files#2]
**Steps to reproduce:**
1. Open folder in Atom.
2. Double click on docx file in tree view pane.

**Atom Version**: 1.0.11
**System**: Microsoft Windows 10 Pro
**Thrown From**: [open-unsupported-files](https://github.com/skandasoft/open-unsupported-files) package, v1.0.10
### Stack Trace

Uncaught TypeError: Cannot read property 'data-path' of undefined

```
At /C:/Users/Shawn/.atom/packages/open-unsupported-files/lib/open-unsupported-files.coffee:32

TypeError: Cannot read property 'data-path' of undefined
  at TreeView.tv.entryClicked (C:\Users\Shawn\.atom\packages\open-unsupported-files\lib\open-unsupported-files.coffee:18:11)
  at tree-view-file.<anonymous> (C:\Users\Shawn\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\tree-view\lib\tree-view.js:183:26)
  at space-pen-div.jQuery.event.dispatch (C:\Users\Shawn\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at space-pen-div.elemData.handle (C:\Users\Shawn\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```
### Commands

```
```
### Config

``` json
{
  "core": {},
  "open-unsupported-files": {}
}
```
### Installed Packages

``` coffee
# User
language-vb, v0.1.0-pre1
open-unsupported-files, v1.0.10

# Dev
No dev packages
```

**Comment by Getron** [comment]
+1

**Comment by skandasoft** [comment]
I will get on to this as soon I can..I just changed this since there was change in atom-tree api..

**Comment by skandasoft** [comment]
Unfortunately I am not able to repeat it. But I have a catch around the exception. I will see if I can raise this up in the tree github.

https://github.com/atom/tree-view/issues/584

**Comment by skandasoft** [comment]
I have updated version on github..but for some reason I am not able to update.I will figure out why till then you free to clone the latest from github and try it out..let me know if you have any suggestions

**Comment by shawnbmiller** [comment]
I tried putting together a fix. I tested it briefly and it works for me on Windows 7 and Ubuntu 14.04 with a docx file.  skandasoft/open-unsupported-files/pull/3

**Comment by skandasoft** [comment]
thanks shawn. I merge as I get to it..

**Comment by yankeeinlondon** [comment]
love the intent of this package but this problem has got me too (on OSX)

**Comment by skandasoft** [comment]
taken care. check the latest version. thanks @shawnbmiller
