### ISSUE TITLE
Failed to load the OPEN-unsupported-files package

### ISSUE THREAD

**Issue by cjpoor** [skandasoft/open-unsupported-files#4]
Enter steps to reproduce below:  1. ... 2. ... **Atom Version**: 1.0.19 **System**: Mac OS X 10.10.5 **Thrown From**:  OPEN-unsupported-files  https://github.com/skandasoft/OPEN-unsupported-files  package, v1.0.12 ### Stack Trace Failed to load the OPEN-unsupported-files package     At Cannot find module  atom-utils  Error: Cannot find module  atom-utils  at Module._resolveFileNAME  module.js:334:15  at FUNCTION.Module._resolveFileNAME  /Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52  at FUNCTION.Module._load  module.js:284:25  at Module.require  module.js:363:17  at require  module.js:382:17  at Object. anonymous>  /Users/christopherpoor/.atom/packages/OPEN-unsupported-files/lib/OPEN-unsupported-files.coffee:2:21  at Object. anonymous>  /Users/christopherpoor/.atom/packages/OPEN-unsupported-files/lib/OPEN-unsupported-files.coffee:1:1  at Module._compile  module.js:428:26  at Object.DEFINEPROPERTY.value  as .coffee   /Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21  at Module.load  module.js:353:32      ### Commands         ### Config    json { core : { disabledPackages :   typeWRITEr , notebook , project-sidebar , org , markdown-format , maximize-panes , move-by-paragraph , trailing-semicolon , Clean2 , markdown-preview-pandoc , markdown-deluxe , unsaved-changes , highlight-selected , keybinding-cheatsheet , last-cursor-position , local-history , move-panes , pdf-view , save-session , smart-quotes-plus , sort-lines , swap-panes , synced-sidebar , tabs-to-spaces , tasks , tree-view-OPEN-files , wordcount , markdown-toc , asciidoc-preview , foldingtext-markdown , markdown-mindmap , autocomplete-atom-api  , themes :   one-dark-ui , pen-paper-coffee-syntax  , excludeVcsIgnoredPaths : false } }     ### Installed Packages    coffee # User .bin, vundefined academic, v0.34.1 atom-typescript, v7.1.5 atomatigit, v1.5.4 autocomplete-bibtex, v0.6.1 autocomplete-paths, v1.0.2 autohide-tree-view, v0.24.5 file-icons, v1.6.9 foldingtext-for-atom, v0.9.2 highlight-selected, v0.10.1 language-asciidoc, v0.12.0 language-diff, v0.3.1 language-restructuredtext, v0.9.0 linter, v1.8.1 markdown-preview-plus, v2.2.0 markdown-scroll-sync, v0.4.2 markdown-table-formatter, v2.5.3 minimap, v4.13.4 minimap-codeglance, v0.4.2 minimap-highlight-selected, v4.3.1 OPEN-unsupported-files, v1.0.12 pen-paper-coffee-syntax, v0.10.3 project-manager, v2.6.1 project-ring, v0.35.2 rst-preview-pandoc, v0.1.11 tool-bar, v0.1.9 # Dev No dev packages

**Comment by skandasoft** [comment]
updated the dependency. can you try installing again.

**Comment by cjpoor** [comment]
This seems to be working now. Thanks.
