### ISSUE TITLE
Getting error when selecting folders in tree view

### ISSUE THREAD

**Issue by ghost** [skandasoft/open-unsupported-files#8]
Error: Uncaught RangeError: Maximum call stack size exceeded 

Steps: When I touch a folder under tree view. There was really only one more file inside the folder. The stack trace error is huge, too big to paste here. 

I don't think this problem was occuring before, I just updated to your newest release. 

Windows 10, 64bit
Atom: 1.6.2

![animation](https://cloud.githubusercontent.com/assets/3500392/14450497/be6842da-0033-11e6-970d-b61877c95e1e.gif)

**Comment by skandasoft** [comment]
can you check the latest patch
